# Generated by Django 5.1.4 on 2024-12-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='source_website',
            new_name='source_url',
        ),
    ]
