# Generated by Django 5.1.4 on 2024-12-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_rename_source_website_job_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source_website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
