# Generated by Django 5.1.4 on 2024-12-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_job_source_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source_website',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
