# Generated by Django 5.1.4 on 2024-12-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_job_source_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
