# Generated by Django 5.1.4 on 2024-12-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
