# Generated by Django 5.1.4 on 2024-12-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scraped_date',
            field=models.CharField(default='22-12-2024', max_length=255),
        ),
    ]
