# Generated by Django 5.1.4 on 2024-12-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_alter_job_scraped_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scraped_date',
            field=models.CharField(max_length=255),
        ),
    ]
