# Generated by Django 5.1.4 on 2024-12-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_alter_job_scraped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
